name: graphql_test
description: DOR Project created by DOR CLI.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.9

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: 8.1.4
  flutter_bloc: 8.1.5
  intl: 0.18.1
  intl_utils: 2.8.7
  json_serializable: 6.7.1
  json_annotation: 4.8.1
  provider: 6.1.2
  fimber_io: 0.7.0
  get_it: 7.7.0
  dio: 5.4.3+1
  flutter_secure_storage: 9.0.0
  injectable: 2.4.1
  collection: 1.18.0
  freezed: 2.5.2
  freezed_annotation: 2.4.1
  equatable: 2.0.5
  retrofit: 4.1.0
  firebase_core: 2.30.0
  firebase_analytics: 10.10.2
  firebase_crashlytics: 3.5.2
  go_router: 13.2.4
  mockito: 5.4.4
  hooked_bloc: 1.5.0
  flutter_hooks: 0.20.5
  ferry: 0.16.0+1
  gql_http_link: 1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  bloc_test: 9.1.7
  injectable_generator: 2.6.1
  retrofit_generator: 8.1.0
  build_runner: 2.4.9
  ferry_generator: 0.10.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/svg/icons/
  - assets/images/illustrations/
  fonts:
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Thin.ttf
    - asset: assets/fonts/Inter-ExtraLight.ttf
    - asset: assets/fonts/Inter-Light.ttf
    - asset: assets/fonts/Inter-Medium.ttf
    - asset: assets/fonts/Inter-Regular.ttf
    - asset: assets/fonts/Inter-SemiBold.ttf
    - asset: assets/fonts/Inter-Bold.ttf
    - asset: assets/fonts/Inter-ExtraBold.ttf
    - asset: assets/fonts/Inter-Black.ttf

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
